# Fichier NATURE TITAN - Version Ultra-Blindée
NATURE_DATA = {
    "🦖 LES DINOSAURES (GÉANTS)": {
        "🦖 T-REX": "Tyrannosaure Rex",
        "🦕 DIPLO": "Diplodocus",
        "🛡️ TRICÉ": "Tricératops",
        "🕊️ PTÉRO": "Ptérodactyle",
        "🦴 STÉGO": "Stégosaure",
        "🌊 MOSA": "Mosasaurus",
        "⚔️ RAPTOR": "Vélociraptor",
        "🐊 SPINO": "Spinosaure",
        "🔨 ANKYLO": "Ankylosaure",
        "🦢 BRACHIO": "Brachiosaure",
        "🥊 PACHY": "Pachycéphalosaure",
        "🔥 CARNO": "Carnotaure",
        "🐦 ARCHÉO": "Archaeopteryx",
        "🛡️ PROTÉ": "Protocératops",
        "🦒 GIGA": "Giganotosaure"
    },
    
    "🦁 LA SAVANE & JUNGLE": {
        "🦁 LION": "Lion",
        "🐯 TIGRE": "Tigre",
        "🐘 ÉLÉPHANT": "Éléphant",
        "🦒 GIRAFE": "Girafe",
        "🦓 ZÈBRE": "Zèbre",
        "🐒 SINGE": "Singe",
        "🦍 GORILLE": "Gorille",
        "🦛 HIPPO": "Hippopotame",
        "🦏 RHINO": "Rhinocéros",
        "🐆 GUÉPARD": "Guépard",
        "🐆 LÉOPARD": "Léopard",
        "🐊 CROCO": "Crocodile",
        "🐍 SERPENT": "Serpent",
        "🐪 CHAMEAU": "Chameau",
        "🐫 DROMADAIRE": "Dromadaire",
        "🦘 KANGOUROU": "Kangourou",
        "🐼 PANDA": "Panda",
        "🐨 KOALA": "Koala",
        "🦥 PARESSEUX": "Paresseux",
        "🦩 FLAMANT": "Flamant Rose",
        "🦜 PERROQUET": "Perroquet",
        "🦚 PAON": "Paon"
    },
    
    "🐬 L'OCÉAN PROFOND": {
        "🐬 DAUPHIN": "Dauphin",
        "🐋 BALEINE": "Baleine",
        "🦈 REQUIN": "Requin",
        "🐙 POULPE": "Poulpe",
        "🐢 TORTUE": "Tortue marine",
        "🦀 CRABE": "Crabe",
        "🦑 CALAMAR": "Calamar",
        "🐠 POISSON": "Poisson Tropical",
        "🐡 POISSON-LUNE": "Poisson globe",
        "🦞 HOMARD": "Homard",
        "🦐 CREVETTE": "Crevette",
        "🐚 COQUILLAGE": "Coquillage",
        "🦭 PHOQUE": "Phoque",
        "🐧 PINGOUIN": "Manchot",
        "🦦 LOUTRE": "Loutre",
        "🐳 ORQUE": "Orque",
        "🌊 RAIE": "Raie Manta",
        "🐎 HIPPOCAMPE": "Hippocampe",
        "⭐ ÉTOILE": "Étoile de mer",
        "🪼 MÉDUSE": "Méduse"
    },
    
    "🐞 PETITES BÊTES": {
        "🦋 PAPILLON": "Papillon",
        "🐝 ABEILLE": "Abeille",
        "🐞 COCCINELLE": "Coccinelle",
        "🐜 FOURMI": "Fourmi",
        "🕷️ ARAIGNÉE": "Araignée",
        "🐛 CHENILLE": "Chenille",
        "🐌 ESCARGOT": "Escargot",
        "🦟 MOUSTIQUE": "Moustique",
        "🦗 CRIQUET": "Criquet",
        "🪲 SCARABÉE": "Scarabée",
        "🦂 SCORPION": "Scorpion",
        "🪱 VER": "Ver de terre",
        "🐉 LIBELLULE": "Libellule",
        "🪳 CACHALOT": "Cafard",
        "🐝 FRELON": "Frelon"
    },
    
    "🌲 FORÊT & CAMPAGNE": {
        "🦊 RENARD": "Renard",
        "🐺 LOUP": "Loup",
        "🐻 OURS": "Ours",
        "🦌 CERF": "Cerf",
        "🐿️ ÉCUREUIL": "Écureuil",
        "🦔 HÉRISSON": "Hérisson",
        "🦉 HIBOU": "Hibou",
        "🦇 CHAUVE-SOURIS": "Chauve-souris",
        "🐰 LAPIN": "Lapin",
        "🐗 SANGLIER": "Sanglier",
        "🦝 RATON": "Raton laveur",
        "🦨 MOUFETTE": "Mouffette",
        "🦦 CASTOR": "Castor",
        "🦅 AIGLE": "Aigle"
    }
}
